version: "3.3"
services:
  redis:
    container_name: redis
    image: redis:7.0.12
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - kafka-network

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    environment:
      - RIPROXYENABLE=true
    depends_on:
      - redis
    networks:
      - kafka-network

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  kafka-network:
    external: true
