version: "3.0"

# Source
# https://viblo.asia/p/elasticsearch-kibana-logstash-tong-quan-cai-dat-va-su-dung-RQqKLRn6l7z
# https://wanago.io/2020/09/07/api-nestjs-elasticsearch/
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=Chainmart123
      - ELASTIC_USERNAME=chainmart
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      - kafka-network

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
      - kafka-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      - SERVER_PORT="5601"
      - ELASTICSEARCH_HOSTS=http://localhost:9200
      - ELASTICSEARCH_USERNAME=chainmart
      - ELASTICSEARCH_PASSWORD=Chainmart123
    networks:
      - elastic
      - kafka-network
    depends_on:
      - es01
      - es02
    ports:
      - 5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data

volumes:
  data01:
    driver: local
  data02:
    driver: local
  kibanadata:
    driver: local

networks:
  elastic:
    driver: bridge
  kafka-network:
    external: true
