version: "3.3"
services:
  chainmart-be:
    container_name: chainmart-be
    image: 376597958889.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-be:latest
    ports:
      - "7000:3000"
    restart: "always"
    env_file:
      - .env
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
