version: "3.3"
services:
  chainmart-be-carts:
    container_name: chainmart-be-carts
    image: 429660533268.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-be-carts:latest
    restart: "always"
    env_file:
      - .env
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true