version: "3.3"
services:
  chainmart-be-products:
    container_name: chainmart-be-products
    image: 376597958889.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-be-products:latest
    restart: "always"
    env_file:
      - .env
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true